# Generated by Django 5.1.2 on 2024-11-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transcaction',
            new_name='Transaction',
        ),
    ]
